server {
  listen 80;
  server_name _;

  location /api/cars {
    proxy_pass http://car-service:8081;
  }

  location /api/services {
    proxy_pass http://service-service:8082;
  }

  location / {
    root /usr/share/nginx/html;
    try_files $uri /index.html;
  }
}
